version: "3.8"

services:
  dogapp-backend:
    build: .
    container_name: dogapp-backend
    restart: unless-stopped
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env.production # Use the production env file
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
      - /var/log/dogapp:/app/logs
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }).on('error', () => { process.exit(1); });",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dogapp-network

networks:
  dogapp-network:
    driver: bridge
